on:
  push:
    branches:
      - master
  #schedule:
  #  - cron:  '*/15 * * * *'

jobs:
  rss_reading_job:
    runs-on: ubuntu-latest
    name: A job to retrieve feeds from RSS
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'davidepastore/lecceprima-rss-db'
        path: 'lecceprima-rss-db'
    - name: Retrieve feeds from RSS
      id: hello
      uses: davidepastore/lecceprima-action@master
      with:
        db-directory: './lecceprima-rss-db'
    - run: |
        cd "$GITHUB_WORKSPACE/lecceprima-rss-db"
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if [ -n "$(git status --porcelain)" ]; then
          echo "There are changes";
          git commit -m "Updating RSS feeds"
          git push origin
        else
          echo "No changes";
        fi
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"