on:
  push:
    branches:
      - master
  #schedule:
  #  - cron:  '*/15 * * * *'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'davidepastore/lecceprima-rss-db'
    - name: Hello world action step
      id: hello
      uses: davidepastore/lecceprima-action@v0.1.0
      with:
        db-directory: './lecceprima-rss-db'
    - run: |
        cd lecceprima-rss-db
        git add -A
        git commit -m "Updating RSS feeds"
        if [ -n "$(git status --porcelain)" ]; then
          echo "There are changes";
        else
          echo "No changes";
        fi
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"