on:
  push:
    branches:
      - master
  #schedule:
  #  - cron:  '*/15 * * * *'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'davidepastore/lecceprima-rss-db'
        path: 'lecceprima-rss-db'
    - name: Hello world action step
      id: hello
      uses: davidepastore/lecceprima-action@master
      with:
        db-directory: './lecceprima-rss-db'
    - run: |
        cd "$GITHUB_WORKSPACE/lecceprima-rss-db"
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Updating RSS feeds" -a
        git push origin
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"